title: "Aircraft Design"
author: "CODE Lab"
copyright: "2025"

execute:
  execute_notebooks: "off"

repository:
  url: "https://github.com/ComputationalDesignLab/aircraft-design"
  path_to_book: "book"

html:
  use_repository_button: true

launch_buttons:
  notebook_interface: "jupyterlab"
