title: "Aircraft Design"
author: "Leifur Leifsson (leifur[at]purdue.edu)"
copyright: "2025"

execute:
  execute_notebooks: "off"

repository:
  url: "https://github.com/ComputationalDesignLab/aircraft-design"
  path_to_book: "book"

launch_buttons:
  notebook_interface: "jupyterlab"
